name: "🐛 Bug Report"
description: Add a bug report to the issue tracker.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: current
    attributes:
      label: "Current Behaviour"
      description: Please describe what is currently happening.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behaviour"
      description: Please describe what you expect to happen.
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots / Screen Recordings"
      description: If applicable, add screenshots / screen recordings to help explain your problem.
      value: |
        Paste, drag and drop, or click option below to add your files here.
    validations:
      required: false
  - type: dropdown
    id: device
    attributes:
      label: "Device"
      description: What device are you seeing the problem on?
      multiple: true
      options:
        - iPhone 11
        - iPhone 13
        - iPhone 15
        - iPhone 15 Pro Max
        - Android Phone
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: Which OS is on your device?
      multiple: true
      options:
        - iOS 17.5.1
        - Android
    validations:
      required: true
