name: "🐛 Bug Report"
description: Add a bug report to the issue tracker.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots / Screen Recordings"
      description: If applicable, add screenshots / screen recordings to help explain your problem.
      value: |
        Paste, drag and drop, or click option below to add your files here.
    validations:
      required: false
  - type: dropdown
    id: device
    attributes:
      label: "Device"
      description: What device are you seeing the problem on?
      multiple: true
      options:
        - iPhone
        - Android Phone
        - iOS emulator
        - Android emulator
    validations:
      required: true
